In [0]:
# !pip install tensorflow-gpu

In [0]:
import tensorflow as tf

print(tf.__version__)

2.0.0


In [0]:
dataset = tf.data.Dataset.range(10)

for val in dataset:
    print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [0]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1)

for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy(), end=" ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [0]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)

for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy(), end=" ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [0]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window:window.batch(5))
print(dataset)
for window in dataset:
    print(window)
    print()

<FlatMapDataset shapes: (None,), types: tf.int64>
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)

tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int64)

tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int64)

tf.Tensor([4 5 6 7 8], shape=(5,), dtype=int64)

tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)



In [0]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window:window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)

for x, y in dataset:
    print(x.numpy(), y.numpy())

[5 6 7 8] [9]
[1 2 3 4] [5]
[4 5 6 7] [8]
[2 3 4 5] [6]
[0 1 2 3] [4]
[3 4 5 6] [7]


In [0]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window:window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)

for x, y in dataset:
    print("x: ", x.numpy())
    print("y: ", y.numpy())

x:  [[1 2 3 4]
 [5 6 7 8]]
y:  [[5]
 [9]]
x:  [[2 3 4 5]
 [0 1 2 3]]
y:  [[6]
 [4]]
x:  [[4 5 6 7]
 [3 4 5 6]]
y:  [[8]
 [7]]
